runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  static_files: email-signature-generator/index.html
  upload: email-signature-generator/index.html
- url: /
  static_dir: email-signature-generator