image: itskigen/alpine-gcloud-sdk

pipelines:
  default:
    - step:
        name: Build & Test.
        script: 
          - echo "skipped for now"
  branches:
    develop:
      - step:
          name: Build & Test. 
          script:
            - echo "skipped for now"
      - step: 
          name: Deploy to Staging 
          deployment: staging
          script: 
            # Read & decode authentication file. -> Instructions here: https://confluence.atlassian.com/bitbucket/deploy-to-google-cloud-900820342.html
            - echo $GCLOUD_API_KEYFILE | base64 -d  > ./gcloud-api-key.json
            - gcloud auth activate-service-account --key-file gcloud-api-key.json
            - gcloud config set project $GCLOUD_PROJECT_TEST
            - gcloud app deploy app.yaml